# Generated by Django 4.0.4 on 2022-06-01 01:04

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consultorio', '0004_alter_cita_medica_fecha'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partidos',
            fields=[
                ('uniqueId', models.AutoField(primary_key=True, serialize=False)),
                ('ubicacion', models.CharField(max_length=500)),
                ('fecha', models.DateField(default=datetime.datetime.now)),
                ('diagnostico', models.CharField(max_length=1000, null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Paciente',
            new_name='Jugador',
        ),
        migrations.RenameModel(
            old_name='Doctor',
            new_name='Profesor',
        ),
        migrations.DeleteModel(
            name='Cita_medica',
        ),
        migrations.AddField(
            model_name='partidos',
            name='jugador_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultorio.jugador'),
        ),
        migrations.AddField(
            model_name='partidos',
            name='profesor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultorio.profesor'),
        ),
    ]
